spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      initialization-fail-timeout: 0

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    test-rollback-on-update: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true